version: '3'

services:
  # mysql
  go-rest-api-db:
    image: mysql:8.0
    container_name: go-rest-api-mysql8
    environment:
      MYSQL_DATABASE: go-rest-api
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "13326:3306"
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/mysql:/etc/mysql/conf.d
      - mysql-volume:/var/lib/mysql  # `docker volume create go-rest-api-mysql8_volume`を予め実行しておく
      
volumes:
  mysql-volume:
    external:
      name: go-rest-api-mysql8_volume
